Any metrical properties represented by using the pseudo-Euclidean axiom can be represented with the Euclidean axiom.

In [154]:
from gc_utils import *

alg = Algebra(5)
ga2 = Algebra(2)
locals().update(alg.blades)

In [155]:
# 2d general linear transform
def random_linear_trans(alg: Algebra):
    matrix = np.random.rand(alg.d, alg.d)
    return matrix2trans(matrix, alg)

def random_ortho_trans(alg: Algebra):
    from scipy.stats import ortho_group
    matrix = ortho_group.rvs(dim=alg.d)
    return matrix2trans(matrix, alg)

f = random_linear_trans(ga2)
x = random_r_blade(1, ga2)
f(x)

0.63 𝐞₁ + 0.81 𝐞₂

In [156]:
# 2d polar decomposition
# f = SUU
df = derivative(f, x, ga2, grade=1)
UU = normalize(df)
S = lambda x: UU * f(x)
S(x)*UU, f(x)

(0.63 𝐞₁ + 0.81 𝐞₂, 0.63 𝐞₁ + 0.81 𝐞₂)

In [157]:
# UU is rotor, S is symmetric
UU, curl(S, x, ga2, grade=1)

(0.816 + 0.579 𝐞₁₂, )

In [158]:
#6.3 remove the condition of 2 dimension
a, b, x = random_r_vectors(3, alg)
g = lambda x: x + (x|a)*b
abframe = [a,b]
r_frame = reciprocal(abframe)
dg = 2 + a*b
derivative(g, x, alg, grade=1, frame=abframe, r_frame=r_frame), dg

(4.07 + -0.304 𝐞₁₂ + -0.435 𝐞₁₃ + -0.0886 𝐞₁₄ + -0.261 𝐞₁₅ + -0.354 𝐞₂₃ + 0.152 𝐞₂₄ + 0.0986 𝐞₂₅ + 0.32 𝐞₃₄ + 0.446 𝐞₃₅ + -0.102 𝐞₄₅ + -8.14e-17 𝐞₁₂₃₄ + 5.32e-17 𝐞₁₂₃₅ + 1.08e-16 𝐞₁₂₄₅ + -8.15e-17 𝐞₁₃₄₅ + -8.19e-17 𝐞₂₃₄₅,
 4.07 + -0.304 𝐞₁₂ + -0.435 𝐞₁₃ + -0.0886 𝐞₁₄ + -0.261 𝐞₁₅ + -0.354 𝐞₂₃ + 0.152 𝐞₂₄ + 0.0986 𝐞₂₅ + 0.32 𝐞₃₄ + 0.446 𝐞₃₅ + -0.102 𝐞₄₅)

In [159]:
#6.3
dg_norm = norm(dg)
UU = dg / dg_norm
U = simple_rotor_sqrt(UU)
S = lambda x: U.sw(g(x))
curl(S, x, alg, grade=1), U.reverse().sw(S(x)), g(x)

(5.55e-10 𝐞₁₃ + -4.44e-10 𝐞₁₄ + 5.55e-10 𝐞₁₅ + -3.33e-10 𝐞₂₃ + -4.44e-10 𝐞₂₅ + -2.78e-10 𝐞₃₄ + -1.11e-10 𝐞₃₅ + 5.55e-11 𝐞₄₅,
 1.33 𝐞₁ + 1.46 𝐞₂ + 0.716 𝐞₃ + 0.985 𝐞₄ + 1.24 𝐞₅ + -1.3e-18 𝐞₁₂₃₄₅,
 1.33 𝐞₁ + 1.46 𝐞₂ + 0.716 𝐞₃ + 0.985 𝐞₄ + 1.24 𝐞₅)

In [160]:
#6.6
frame = alg.frame
i, j = 1, 3
aij = (1/np.sqrt(2))*(frame[i] + frame[j])
[aij.sw(x) for x in frame]

[-1.0 𝐞₁, 1.0 𝐞₄, -1.0 𝐞₃, 1.0 𝐞₂, -1.0 𝐞₅]

In [161]:
#6.7
alpha = 3
Sij = lambda x: x + (alpha * (x|frame[i]) * frame[j])
[Sij(x) for x in frame]

[1 𝐞₁, 1 𝐞₂ + 3 𝐞₄, 1 𝐞₃, 1 𝐞₄, 1 𝐞₅]

In [162]:
#7.2
g = random_linear_trans(alg)
g_ = lambda x, y: x | g(y)
derivative(lambda x: g_(x, b), x, alg, grade=1), g(b)

(1.34 𝐞₁ + 1.73 𝐞₂ + 2.35 𝐞₃ + 1.63 𝐞₄ + 1.87 𝐞₅,
 1.34 𝐞₁ + 1.73 𝐞₂ + 2.35 𝐞₃ + 1.63 𝐞₄ + 1.87 𝐞₅)

In [163]:
# check nonsingular
outermorphism(g, alg.pseudoscalar((1,)), alg)

-0.255 𝐞₁₂₃₄₅

In [198]:
#7.5 orthogonal transformation is its isometry
def check_isometry(f, alg, g=None, tol=1e-6):
    x, y = random_r_vectors(2, alg)
    if g:
        return max_diff(f(x) | g(f(y)), x | g(y)) < tol
    return max_diff(f(x) | f(y), x | y) < tol
f = random_ortho_trans(alg)
check_isometry(f, alg, f)

True

In [165]:
# skew bilinear form
gm = skew_part(g, alg)
G = simplicial_derivative(lambda vectors: vectors[0] | gm(vectors[1]), np.zeros(2), alg)
x | gm(b), x | (b | G)

(-0.14, -0.14)

In [166]:
#7.6b f is not an isometry of gm
adjoint_outermorphism(f, G, alg), G

(0.0155 𝐞₁₂ + -0.205 𝐞₁₃ + 0.0183 𝐞₁₄ + 0.272 𝐞₁₅ + -0.243 𝐞₂₃ + -0.322 𝐞₂₄ + -0.0148 𝐞₂₅ + -0.305 𝐞₃₄ + 0.388 𝐞₃₅ + -0.311 𝐞₄₅,
 -0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅)

In [167]:
#7.8 the inverse of gm
blades = bivector_split(G, alg)
gm(sum(-x | blade/normsq(blade) for blade in blades)), x

(0.659 𝐞₁ + 0.539 𝐞₂ + 0.186 𝐞₃ + 0.404 𝐞₄ + 0.324 𝐞₅,
 0.676 𝐞₁ + 0.56 𝐞₂ + 0.194 𝐞₃ + 0.398 𝐞₄ + 0.257 𝐞₅)

In [168]:
#7.12 assume splitted blades are normal
blades_norm = [norm(b) for b in blades]
blades = [b / n for b, n in zip(blades, blades_norm)]
gprod(blades)

1.49e-16 + 1.15e-16 𝐞₁₂ + -3.07e-17 𝐞₁₃ + 1.65e-17 𝐞₁₄ + 6.95e-17 𝐞₁₅ + -8.67e-18 𝐞₂₃ + -9.28e-17 𝐞₂₄ + 4.55e-17 𝐞₂₅ + 2.19e-16 𝐞₃₄ + 2.6e-18 𝐞₃₅ + -2.78e-17 𝐞₄₅ + 0.918 𝐞₁₂₃₄ + -0.0807 𝐞₁₂₃₅ + -0.115 𝐞₁₂₄₅ + 0.292 𝐞₁₃₄₅ + -0.23 𝐞₂₃₄₅

In [169]:
#7.17
theta = np.random.rand(2)
rotors = [blade_exp(t*blade) for t, blade in zip(theta, blades)]
[(U.sw(G), G) for U in rotors for G in blades]

[(0.235 𝐞₁₂ + 0.144 𝐞₁₃ + 0.723 𝐞₁₄ + 0.0291 𝐞₁₅ + 0.0281 𝐞₂₃ + -0.496 𝐞₂₄ + -0.0117 𝐞₂₅ + -0.39 𝐞₃₄ + -0.0107 𝐞₃₅ + 0.0253 𝐞₄₅,
  0.235 𝐞₁₂ + 0.144 𝐞₁₃ + 0.0281 𝐞₂₃ + 0.723 𝐞₁₄ + -0.496 𝐞₂₄ + -0.39 𝐞₃₄ + 0.0291 𝐞₁₅ + -0.0117 𝐞₂₅ + -0.0107 𝐞₃₅ + 0.0253 𝐞₄₅),
 (-0.36 𝐞₁₂ + 0.462 𝐞₁₃ + 0.0275 𝐞₁₄ + -0.0591 𝐞₁₅ + 0.656 𝐞₂₃ + -0.138 𝐞₂₄ + 0.184 𝐞₂₅ + 0.227 𝐞₃₄ + -0.344 𝐞₃₅ + 0.00852 𝐞₄₅,
  -0.36 𝐞₁₂ + 0.462 𝐞₁₃ + 0.656 𝐞₂₃ + 0.0275 𝐞₁₄ + -0.138 𝐞₂₄ + 0.227 𝐞₃₄ + -0.0591 𝐞₁₅ + 0.184 𝐞₂₅ + -0.344 𝐞₃₅ + 0.00852 𝐞₄₅),
 (0.235 𝐞₁₂ + 0.144 𝐞₁₃ + 0.723 𝐞₁₄ + 0.0291 𝐞₁₅ + 0.0281 𝐞₂₃ + -0.496 𝐞₂₄ + -0.0117 𝐞₂₅ + -0.39 𝐞₃₄ + -0.0107 𝐞₃₅ + 0.0253 𝐞₄₅,
  0.235 𝐞₁₂ + 0.144 𝐞₁₃ + 0.0281 𝐞₂₃ + 0.723 𝐞₁₄ + -0.496 𝐞₂₄ + -0.39 𝐞₃₄ + 0.0291 𝐞₁₅ + -0.0117 𝐞₂₅ + -0.0107 𝐞₃₅ + 0.0253 𝐞₄₅),
 (-0.36 𝐞₁₂ + 0.462 𝐞₁₃ + 0.0275 𝐞₁₄ + -0.0591 𝐞₁₅ + 0.656 𝐞₂₃ + -0.138 𝐞₂₄ + 0.184 𝐞₂₅ + 0.227 𝐞₃₄ + -0.344 𝐞₃₅ + 0.00852 𝐞₄₅,
  -0.36 𝐞₁₂ + 0.462 𝐞₁₃ + 0.656 𝐞₂₃ + 0.0275 𝐞₁₄ + -0.138 𝐞₂₄ + 0.227 𝐞₃₄ + -0.0591 𝐞₁₅ + 0.184 𝐞

In [170]:
#7.18
first_vecs = [blade_split(blade, alg)[0] for blade in blades]
first_vecs = [normalize(v) for v in first_vecs]
second_vecs = [v | blade for v, blade in zip(first_vecs, blades)]
inter_plane_rotors = [simple_rotor_sqrt(a * b) for a, b in (first_vecs, second_vecs)]
U = gprod(inter_plane_rotors)
terms_ratio(U.sw(blades[0]), blades[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [171]:
f"{x[1:]}"

'(0.5599948809267774, 0.1941611108820589, 0.39841780216681666, 0.25742784815426867)'

In [172]:
G_normalized = sum(blades)
G_normalized, U.sw(G_normalized)

(-0.125 𝐞₁₂ + 0.606 𝐞₁₃ + 0.751 𝐞₁₄ + -0.03 𝐞₁₅ + 0.684 𝐞₂₃ + -0.634 𝐞₂₄ + 0.173 𝐞₂₅ + -0.163 𝐞₃₄ + -0.355 𝐞₃₅ + 0.0338 𝐞₄₅,
 -0.125 𝐞₁₂ + 0.606 𝐞₁₃ + 0.751 𝐞₁₄ + -0.03 𝐞₁₅ + 0.684 𝐞₂₃ + -0.634 𝐞₂₄ + 0.173 𝐞₂₅ + -0.163 𝐞₃₄ + -0.355 𝐞₃₅ + 0.0338 𝐞₄₅)

In [173]:
# we can recover this "normalization"
sum(P(G_normalized, b) * n for b, n in zip(blades, blades_norm)), G

(-0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅,
 -0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅)

In [174]:
#7.21 zero if not onto the decomposed blades 
sympletic_basis = first_vecs + second_vecs
list(zip((v | (w | G_normalized) for v, w in product(sympletic_basis, repeat=2)), (product(['f', 'fp', 's', 'sp'], repeat=2))))

[(-1.79e-17, ('f', 'f')),
 (1.65e-17, ('f', 'fp')),
 (-1.0, ('f', 's')),
 (-2.34e-17, ('f', 'sp')),
 (-8.67e-18, ('fp', 'f')),
 (-8.33e-17, ('fp', 'fp')),
 (-1.08e-16, ('fp', 's')),
 (-1.0, ('fp', 'sp')),
 (1.0, ('s', 'f')),
 (1.06e-16, ('s', 'fp')),
 (-6.43e-17, ('s', 's')),
 (4.34e-17, ('s', 'sp')),
 (1.11e-16, ('sp', 'f')),
 (1.0, ('sp', 'fp')),
 (-7.03e-17, ('sp', 's')),
 (, ('sp', 'sp'))]

In [175]:
# Recover the normalization
[gm(v)/n for v, n in zip(sympletic_basis, blades_norm*2)], sympletic_basis

([2.48e-17 𝐞₁ + 0.303 𝐞₂ + 0.186 𝐞₃ + 0.934 𝐞₄ + 0.0376 𝐞₅,
  0.46 𝐞₁ + 7.87e-17 𝐞₂ + 0.838 𝐞₃ + -0.176 𝐞₄ + 0.235 𝐞₅,
  -0.775 𝐞₁ + 0.459 𝐞₂ + 0.373 𝐞₃ + -0.224 𝐞₄ + 0.0181 𝐞₅,
  -0.368 𝐞₁ + -0.783 𝐞₂ + 0.333 𝐞₃ + 0.201 𝐞₄ + -0.317 𝐞₅],
 [0.775 𝐞₁ + -0.459 𝐞₂ + -0.373 𝐞₃ + 0.224 𝐞₄ + -0.0181 𝐞₅,
  0.368 𝐞₁ + 0.783 𝐞₂ + -0.333 𝐞₃ + -0.201 𝐞₄ + 0.317 𝐞₅,
  -2.11e-17 𝐞₁ + 0.303 𝐞₂ + 0.186 𝐞₃ + 0.934 𝐞₄ + 0.0376 𝐞₅,
  0.46 𝐞₁ + 0.838 𝐞₃ + -0.176 𝐞₄ + 0.235 𝐞₅])

In [176]:
#7.26a symplectic transformations of gm (isometries of skew bilinear form)
# conditions: unity and sympletic basis
translation = lambda x: (
    x + 
    2*(x|second_vecs[1]) * first_vecs[1] + 
    3*(x|second_vecs[0]) * first_vecs[0]
    )

outermorphism(translation, G_normalized, alg), G_normalized, outermorphism(translation, G, alg), G

(-0.125 𝐞₁₂ + 0.606 𝐞₁₃ + 0.751 𝐞₁₄ + -0.03 𝐞₁₅ + 0.684 𝐞₂₃ + -0.634 𝐞₂₄ + 0.173 𝐞₂₅ + -0.163 𝐞₃₄ + -0.355 𝐞₃₅ + 0.0338 𝐞₄₅,
 -0.125 𝐞₁₂ + 0.606 𝐞₁₃ + 0.751 𝐞₁₄ + -0.03 𝐞₁₅ + 0.684 𝐞₂₃ + -0.634 𝐞₂₄ + 0.173 𝐞₂₅ + -0.163 𝐞₃₄ + -0.355 𝐞₃₅ + 0.0338 𝐞₄₅,
 -0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅,
 -0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅)

In [177]:
#7.26b
rotation = lambda x: (
    x + 
    4*((x|first_vecs[1]) * second_vecs[1] + (x|second_vecs[0]) * first_vecs[0])
    )

outermorphism(rotation, G_normalized, alg), G_normalized, outermorphism(rotation, G, alg), G

(-0.125 𝐞₁₂ + 0.606 𝐞₁₃ + 0.751 𝐞₁₄ + -0.03 𝐞₁₅ + 0.684 𝐞₂₃ + -0.634 𝐞₂₄ + 0.173 𝐞₂₅ + -0.163 𝐞₃₄ + -0.355 𝐞₃₅ + 0.0338 𝐞₄₅,
 -0.125 𝐞₁₂ + 0.606 𝐞₁₃ + 0.751 𝐞₁₄ + -0.03 𝐞₁₅ + 0.684 𝐞₂₃ + -0.634 𝐞₂₄ + 0.173 𝐞₂₅ + -0.163 𝐞₃₄ + -0.355 𝐞₃₅ + 0.0338 𝐞₄₅,
 -0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅,
 -0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅)

In [178]:
#7.26c
outermorphism(lambda x: rotation(translation(x)), G, alg), G

(-0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅,
 -0.172 𝐞₁₂ + 0.376 𝐞₁₃ + 0.272 𝐞₁₄ + -0.0315 𝐞₁₅ + 0.472 𝐞₂₃ + -0.271 𝐞₂₄ + 0.126 𝐞₂₅ + 0.0237 𝐞₃₄ + -0.246 𝐞₃₅ + 0.0148 𝐞₄₅)

In [179]:
#7.28
gp = sym_part(g, alg)
matrix = trans2matrix(gp, alg)
eigvalues, eigvecs = np.linalg.eigh(matrix)
eigvecs = [alg.vector(v) for v in eigvecs.transpose()]
neg_vecs, pos_vecs, null_vecs = [], [], []
for e, v in zip(eigvalues, eigvecs):
    if e < -1e-6:
        neg_vecs.append(v)
    elif e > 1e-6:
        pos_vecs.append(v)
    else:
        null_vecs.append(v)

neg_blade = wedge(neg_vecs)
nv_sign = (-1) ** len(neg_vecs) 
c = lambda x: nv_sign*neg_blade.sw(x)
h = lambda x: sum(np.sqrt(abs(e)) * P(x, v) for e, v in zip(eigvalues, eigvecs))

x | gp(b), h(x)|c(h(b)), c(x)|h(h(b))

(3.6,
 3.6 + -3.78e-18 𝐞₁₂₃₄ + 5.64e-18 𝐞₁₂₃₅ + -3.46e-18 𝐞₁₂₄₅ + 5.39e-18 𝐞₁₃₄₅ + -5.35e-18 𝐞₂₃₄₅,
 3.6 + -3.03e-17 𝐞₁₂₃₄ + 2.67e-17 𝐞₁₂₃₅ + -2.31e-17 𝐞₁₂₄₅ + 3.1e-17 𝐞₁₃₄₅ + -2.37e-17 𝐞₂₃₄₅)

In [196]:
#7.28 If the symmetric transformation is positive definite (Euclidean metric)
gpp = lambda x: sum(abs(e) * P(x, v) for e, v in zip(eigvalues, eigvecs))
hinv = lambda x: sum(1/np.sqrt(abs(e)) * P(x, v) for e, v in zip(eigvalues, eigvecs))
r = 3 # a arbitrary integer <= n
O = normalize(random_versor(r, alg))
f = lambda x: -hinv(O.sw(h(x)))
check_isometry(f, alg, gpp), x, f(x)

(True,
 0.676 𝐞₁ + 0.56 𝐞₂ + 0.194 𝐞₃ + 0.398 𝐞₄ + 0.257 𝐞₅,
 1.08 𝐞₁ + 1.2 𝐞₂ + -2.66 𝐞₃ + -1.05 𝐞₄ + 0.0712 𝐞₅ + 9.66e-35 𝐞₁₂₃ + -7.27e-34 𝐞₁₂₄ + -1.54e-33 𝐞₁₃₄ + 1.82e-34 𝐞₁₃₅ + 7.02e-34 𝐞₁₄₅ + -4.27e-34 𝐞₂₃₄ + 3.3e-33 𝐞₂₃₅ + -8.17e-34 𝐞₂₄₅ + -6.81e-34 𝐞₃₄₅)

In [197]:
# But if gp is not positive definite, an orthogonal transform may not be an isometry
f = lambda x: hinv(O.sw(h(x)))
check_isometry(f, alg, gp), f(x)

(False,
 -1.08 𝐞₁ + -1.2 𝐞₂ + 2.66 𝐞₃ + 1.05 𝐞₄ + -0.0712 𝐞₅ + -9.66e-35 𝐞₁₂₃ + 7.27e-34 𝐞₁₂₄ + 1.54e-33 𝐞₁₃₄ + -1.82e-34 𝐞₁₃₅ + -7.02e-34 𝐞₁₄₅ + 4.27e-34 𝐞₂₃₄ + -3.3e-33 𝐞₂₃₅ + 8.17e-34 𝐞₂₄₅ + 6.81e-34 𝐞₃₄₅)

In [182]:
#7.33 Signature: the inner product under metric c splits into two part, according to neg_blade
def ortho_split(x, A):
    xp = P(x, A)
    return xp, x-xp

xp, xo = ortho_split(x, neg_blade)
bp, bo = ortho_split(b, neg_blade)
neg_blade, x | c(b), (xo | bo) - (xp | bp)


(-0.0974 𝐞₁₂ + 0.462 𝐞₁₃ + -0.123 𝐞₁₄ + -0.154 𝐞₁₅ + -0.694 𝐞₂₃ + 0.19 𝐞₂₄ + 0.305 𝐞₂₅ + -0.0197 𝐞₃₄ + -0.346 𝐞₃₅ + 0.0858 𝐞₄₅,
 1.34 + -8.04e-18 𝐞₁₂₃₄ + 1.24e-17 𝐞₁₂₃₅ + -6.06e-18 𝐞₁₂₄₅ + 1.75e-17 𝐞₁₃₄₅ + -2.11e-17 𝐞₂₃₄₅,
 1.34)

In [195]:
# If R is a rotor (see next section) preserves the reflected subspace (neg_blade)
# Then R is an isometry
R = 1
if len(neg_vecs) >= 2:
    R *= blade_exp(3.3 * wedge(neg_vecs[:2]))
if len(pos_vecs) >= 2:
    R *= blade_exp(5.5 * wedge(pos_vecs[-2:]))
f = lambda x: hinv(R.sw(h(x)))

R.sw(neg_blade), neg_blade, check_isometry(f, alg, gp)

(-0.0974 𝐞₁₂ + 0.462 𝐞₁₃ + -0.123 𝐞₁₄ + -0.154 𝐞₁₅ + -0.694 𝐞₂₃ + 0.19 𝐞₂₄ + 0.305 𝐞₂₅ + -0.0197 𝐞₃₄ + -0.346 𝐞₃₅ + 0.0858 𝐞₄₅,
 -0.0974 𝐞₁₂ + 0.462 𝐞₁₃ + -0.123 𝐞₁₄ + -0.154 𝐞₁₅ + -0.694 𝐞₂₃ + 0.19 𝐞₂₄ + 0.305 𝐞₂₅ + -0.0197 𝐞₃₄ + -0.346 𝐞₃₅ + 0.0858 𝐞₄₅,
 True)

In [184]:
def random_linear_comb(vectors, normalized=True):
    comb = sum(np.random.rand() * v for v in vectors)
    if normalized:
        return normalize(comb)
    return comb

In [199]:
# If R is a spinor preserves the reflected subspace (neg_blade)
# Then R is an isometry
R = 1
if len(neg_vecs) >= 2:
    R *= blade_exp(3.3 * wedge(neg_vecs[:2]))
if len(pos_vecs) >= 2:
    R *= blade_exp(5.5 * wedge(pos_vecs[:2]))
R *= random_linear_comb(pos_vecs)
R *= random_linear_comb(neg_vecs)
f = lambda x: hinv(R.sw(h(x)))

R.sw(neg_blade), neg_blade, check_isometry(f, alg, gp)

(0.0974 𝐞₁₂ + -0.462 𝐞₁₃ + 0.123 𝐞₁₄ + 0.154 𝐞₁₅ + 0.694 𝐞₂₃ + -0.19 𝐞₂₄ + -0.305 𝐞₂₅ + 0.0197 𝐞₃₄ + 0.346 𝐞₃₅ + -0.0858 𝐞₄₅,
 -0.0974 𝐞₁₂ + 0.462 𝐞₁₃ + -0.123 𝐞₁₄ + -0.154 𝐞₁₅ + -0.694 𝐞₂₃ + 0.19 𝐞₂₄ + 0.305 𝐞₂₅ + -0.0197 𝐞₃₄ + -0.346 𝐞₃₅ + 0.0858 𝐞₄₅,
 True)

In [200]:
# Simplify the above as versors
R = gprod(random_linear_comb(pos_vecs) for _ in range(5))
R *= gprod(random_linear_comb(neg_vecs) for _ in range(5))
f = lambda x: hinv(R.sw(h(x)))

R.sw(neg_blade), neg_blade, check_isometry(f, alg, gp)

(-0.0974 𝐞₁₂ + 0.462 𝐞₁₃ + -0.123 𝐞₁₄ + -0.154 𝐞₁₅ + -0.694 𝐞₂₃ + 0.19 𝐞₂₄ + 0.305 𝐞₂₅ + -0.0197 𝐞₃₄ + -0.346 𝐞₃₅ + 0.0858 𝐞₄₅,
 -0.0974 𝐞₁₂ + 0.462 𝐞₁₃ + -0.123 𝐞₁₄ + -0.154 𝐞₁₅ + -0.694 𝐞₂₃ + 0.19 𝐞₂₄ + 0.305 𝐞₂₅ + -0.0197 𝐞₃₄ + -0.346 𝐞₃₅ + 0.0858 𝐞₄₅,
 True)

A versor in G(n-k, k) is an isometry of the inner product. How does this isometry correspond to the isometry of a metric of signature (n-k, k)?

In [204]:
signature = (len(pos_vecs), len(neg_vecs))
pseudo = Algebra(*signature)
locals().update(pseudo.blades)
O = normalize(random_versor(1, pseudo))

signature, check_isometry(lambda x: O.sw(x), pseudo)

((3, 2), True)

In [205]:
blade_names = pseudo.blades.blades.keys()
def parse_e_string(e_string):
    # Extract the numeric part of the string and convert each character to an integer
    return tuple(int(char) - 1 for char in e_string[1:])

[parse_e_string(k) for k in blade_names]

[(),
 (0,),
 (1,),
 (2,),
 (3,),
 (4,),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 3),
 (2, 4),
 (3, 4),
 (0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (0, 2, 3),
 (0, 2, 4),
 (0, 3, 4),
 (1, 2, 3),
 (1, 2, 4),
 (1, 3, 4),
 (2, 3, 4),
 (0, 1, 2, 3),
 (0, 1, 2, 4),
 (0, 1, 3, 4),
 (0, 2, 3, 4),
 (1, 2, 3, 4),
 (0, 1, 2, 3, 4)]

In [206]:
R = 0
bases = pos_vecs + neg_vecs
for key in blade_names:
    indices = parse_e_string(key)
    mv = wedge([bases[i] for i in indices])
    R += O[key] * mv
R = normalize(R)
f = lambda x: hinv(R.sw(h(x)))
check_isometry(f, alg, gp), f(x)

(False, -1.55 𝐞₁ + -2.05 𝐞₂ + 0.317 𝐞₃ + 1.5 𝐞₄ + 0.253 𝐞₅)

So a rotation preserves the reflected subspace is an isometry. Any other isometry? The above we split the space into pos_vecs and neg_vecs. The metric's signature encode such split. The next section we encode the metric into the algebra. So an orthogonal transform becomes an isometry of the vector space.

In [208]:
#8.2 simple reflection
x, y, u = random_r_vectors(3, pseudo)
u = normalize(u)
R = lambda x: - u.sw(x)
R(x) | R(y), x | y

(-0.126, -0.126)

Cartan-Dieudonne theorem: An isometry is a composition of at most d reflections. Identifying invariants of isometries as elements of geometry leads to modern developments.

In [209]:
#8.3 Cartan-Dieudonne theorem: An isometry is a composition of at most d reflections.
k = 3 # k <= d
vectors = random_r_vectors(k, pseudo)
p = sum((v**2)[0] > 0 for v in vectors)
U = gprod(vectors) # a versor, of either even or odd grades
# f = lambda x: (-1) ** k * U * x / U
f = lambda x: (-1) ** p * U.sw(x) / normsq(U) #8.8b
x | y, f(x) | f(y)

(-0.126,
 -0.126 + 5.4e-16 𝐞₁₂₃₄ + 3.44e-16 𝐞₁₂₃₅ + -5.6e-16 𝐞₁₂₄₅ + -2.56e-16 𝐞₁₃₄₅ + 5.7e-17 𝐞₂₃₄₅)

In [210]:
#8.8
def random_versor(r, alg):
    return gprod(random_r_vectors(r, alg))

def random_versor_(r, alg):
    vectors = random_r_vectors(r, alg)
    p = sum((v**2)[0] > 0 for v in vectors)
    return gprod(vectors), p
k = 3
for _ in range(10):
    U, p = random_versor_(k, pseudo)
    U = normalize(U)
    print(k - p, U.reverse() * U)

2 1.0 + -1.11e-16 𝐞₁₂ + -5.55e-17 𝐞₁₃ + 2.5e-16 𝐞₁₄ + -1.04e-17 𝐞₁₅ + -1.05e-16 𝐞₂₄ + -3.33e-16 𝐞₂₅ + 1.11e-16 𝐞₃₅ + -2.22e-16 𝐞₄₅ + 5.55e-17 𝐞₁₂₃₄ + -1.11e-16 𝐞₁₂₃₅ + -1.8e-16 𝐞₁₂₄₅ + -5.55e-17 𝐞₁₃₄₅
2 1.0 + -2.22e-16 𝐞₁₂ + 5.27e-16 𝐞₁₃ + -1.61e-15 𝐞₁₄ + 1.11e-16 𝐞₁₅ + 1.11e-16 𝐞₂₄ + 5.55e-16 𝐞₂₅ + 4.44e-16 𝐞₃₄ + 8.88e-16 𝐞₃₅ + 2.22e-16 𝐞₄₅ + 1.78e-15 𝐞₁₂₃₄ + -2.08e-15 𝐞₁₂₃₅ + 3.89e-16 𝐞₁₂₄₅ + 3.11e-15 𝐞₁₃₄₅ + -2e-15 𝐞₂₃₄₅
0 1.0 + 1.11e-16 𝐞₁₄ + 1.11e-16 𝐞₁₅ + -2.78e-17 𝐞₂₃ + 4.86e-17 𝐞₂₄ + -2.43e-17 𝐞₃₄ + -5.55e-17 𝐞₃₅ + 9.97e-17 𝐞₄₅ + -8.33e-17 𝐞₁₂₃₄ + 1.11e-16 𝐞₁₂₃₅ + 1.11e-16 𝐞₁₂₄₅ + 1.11e-16 𝐞₁₃₄₅ + 3.05e-16 𝐞₂₃₄₅
1 -1.0 + -1.8e-16 𝐞₁₃ + -3.12e-17 𝐞₁₄ + -4.86e-17 𝐞₁₅ + -2.91e-16 𝐞₂₃ + -3.47e-17 𝐞₂₄ + -2.78e-17 𝐞₂₅ + -6.25e-17 𝐞₃₄ + -5.55e-17 𝐞₃₅ + 3.47e-17 𝐞₄₅ + -3.49e-16 𝐞₁₂₃₄ + 8.33e-17 𝐞₁₂₃₅ + 3.58e-18 𝐞₁₂₄₅ + 1.25e-16 𝐞₁₃₄₅ + 2.5e-16 𝐞₂₃₄₅
1 -1.0 + 5.55e-17 𝐞₁₃ + 4.16e-17 𝐞₁₄ + -1.39e-17 𝐞₁₅ + -2.78e-17 𝐞₂₃ + 3.12e-17 𝐞₂₄ + -1.21e-17 𝐞₂₅ + -2.78e-17 𝐞₃₄ + 2.78e-17 𝐞₃₅ + -6.94

In [211]:
# versors (Pin) are 2:1 homomorphisc to orthogonal transformations (O)
U = random_versor(3, pseudo)
U.sw(x), (-U).sw(x)

(-0.27 𝐞₁ + -0.794 𝐞₂ + -0.214 𝐞₃ + -0.581 𝐞₄ + -0.637 𝐞₅ + 1.28e-16 𝐞₁₂₃₄₅,
 -0.27 𝐞₁ + -0.794 𝐞₂ + -0.214 𝐞₃ + -0.581 𝐞₄ + -0.637 𝐞₅ + 1.28e-16 𝐞₁₂₃₄₅)

In [212]:
#8.5
I = pseudo.pseudoscalar((1,))
I.sw(x), x

(0.968 𝐞₁ + 0.352 𝐞₂ + 0.0997 𝐞₃ + 0.669 𝐞₄ + 0.754 𝐞₅,
 0.968 𝐞₁ + 0.352 𝐞₂ + 0.0997 𝐞₃ + 0.669 𝐞₄ + 0.754 𝐞₅)

In [213]:
#8.7 orthogonal transformations (O) with determinant 1 (SO) correspond to even versors (Spin)
for k in range(1,5):
    U = gprod(random_r_vectors(k, pseudo)) # a versor, of either even or odd grades
    f = lambda x: (-1) ** (k*pseudo.d) * U.sw(x)/normsq(U)
    print(k, outermorphism(f, I, pseudo))

1 1.0 𝐞₁₂₃₄₅
2 1.0 𝐞₁₂₃₄₅
3 1.0 𝐞₁₂₃₄₅
4 1.0 𝐞₁₂₃₄₅


In [273]:
#8.9 rotors (Spin+) are a part of even versors (Spin), correpond to a part of SO as rotations (SO+)
def random_even_versor(alg):
    d = alg.d
    if (alg.d % 2):
        d -= 1
    return gprod(random_r_vectors(d, alg))


def random_rotor(alg, max_iter=100, tol=1e-6):
    for _ in range(max_iter):
        S = random_even_versor(alg)
        sign  = (S.reverse().sp(S))[0]
        if sign > 0:
            if S[0] < (-tol):
                S *= -1
            return normalize(S)
        

def random_rotor_count(alg, max_iter=100):
    count = 0
    for _ in range(max_iter):
        S = random_even_versor(alg)
        sign  = (S.reverse().sp(S))[0]
        if sign > 0:
            count += 1
    return count

[(p, q, r, random_rotor_count(Algebra(p, q, r), 2000)/2000) for p, q, r in ((3,1,0),(1,3,0),(4,1,0),(3,0,1),(2,2,0))]

[(3, 1, 0, 0.652),
 (1, 3, 0, 0.653),
 (4, 1, 0, 0.7885),
 (3, 0, 1, 1.0),
 (2, 2, 0, 0.5035)]

versors (Pin) are products of {1, a, b, ab} and a rotor, so to understand the connection of an isometry of an metric tensor and an isometry of an algebra, is to find the connection between G(1,1) and G(2)

In [215]:
#8.12
def random_simple_rotor(alg):
    while True:
        S = random_versor(2, alg)
        sign  = (S.reverse().sp(S))[0]
        if sign > 0:
            return S/norm(S)

In [216]:
#8.13
S = random_simple_rotor(pseudo)
u = normalize(x | S.grade(2))
v = S.sw(u)
v, S ** 2 * u, v ** 2, u ** 2, v * u, S ** 2

(-2.83 𝐞₁ + -3.51 𝐞₂ + -2.92 𝐞₃ + -1.72 𝐞₄ + -4.98 𝐞₅ + 8.67e-18 𝐞₁₂₃₄₅,
 -2.83 𝐞₁ + -3.51 𝐞₂ + -2.92 𝐞₃ + -1.72 𝐞₄ + -4.98 𝐞₅ + -5.63e-17 𝐞₁₂₃ + -2.01e-17 𝐞₁₂₄ + -4.89e-16 𝐞₁₂₅ + -4.56e-17 𝐞₁₃₄ + -4.75e-17 𝐞₁₃₅ + -5.55e-17 𝐞₁₄₅ + -9.46e-17 𝐞₂₃₄ + 2.04e-16 𝐞₂₃₅ + 2e-16 𝐞₂₄₅ + -1.59e-16 𝐞₃₄₅ + -8.09e-18 𝐞₁₂₃₄₅,
 1.0 + 8.65e-17 𝐞₁₂₃₄ + -2.98e-17 𝐞₁₂₃₅ + -5.06e-17 𝐞₁₂₄₅ + 6.08e-17 𝐞₁₃₄₅ + -4.9e-17 𝐞₂₃₄₅,
 1.0,
 2.02 + 0.873 𝐞₁₂ + 0.318 𝐞₁₃ + 0.152 𝐞₁₄ + -0.261 𝐞₁₅ + -0.507 𝐞₂₃ + -0.342 𝐞₂₄ + -1.86 𝐞₂₅ + -0.0364 𝐞₃₄ + -0.829 𝐞₃₅ + -0.426 𝐞₄₅ + 9.49e-18 𝐞₁₂₃₄ + -4.01e-18 𝐞₁₂₃₅ + -7e-18 𝐞₁₂₄₅ + 9.92e-18 𝐞₁₃₄₅ + -5.84e-18 𝐞₂₃₄₅,
 2.02 + 0.873 𝐞₁₂ + 0.318 𝐞₁₃ + 0.152 𝐞₁₄ + -0.261 𝐞₁₅ + -0.507 𝐞₂₃ + -0.342 𝐞₂₄ + -1.86 𝐞₂₅ + -0.0364 𝐞₃₄ + -0.829 𝐞₃₅ + -0.426 𝐞₄₅ + 9.54e-18 𝐞₁₂₃₄ + -5.55e-17 𝐞₁₂₃₅ + -4.16e-17 𝐞₂₃₄₅)

In [217]:
S ** 2 * (S ** 2).reverse(), S * S.reverse()

(1.0 + -1.09e-17 𝐞₁₃ + -4.65e-17 𝐞₁₄ + 1.11e-16 𝐞₁₅ + -1.59e-17 𝐞₂₃ + 3.15e-17 𝐞₂₄ + -9.49e-17 𝐞₂₅ + -1.37e-17 𝐞₃₄ + 2.92e-16 𝐞₃₅ + 1.32e-16 𝐞₄₅ + -7.96e-17 𝐞₁₂₃₄ + -2.25e-16 𝐞₁₂₃₅ + -5.22e-17 𝐞₁₂₄₅ + 5.59e-17 𝐞₁₃₄₅ + -5.03e-17 𝐞₂₃₄₅,
 1.0 + 1.56e-17 𝐞₁₅ + 2.43e-17 𝐞₂₅ + 1.39e-17 𝐞₃₅ + -9.54e-18 𝐞₁₂₃₄ + 5.55e-17 𝐞₁₂₃₅ + 4.16e-17 𝐞₂₃₄₅)

In [218]:
#8.15
(S ** 2).reverse(), u * v, v * u

(2.02 + -0.873 𝐞₁₂ + -0.318 𝐞₁₃ + -0.152 𝐞₁₄ + 0.261 𝐞₁₅ + 0.507 𝐞₂₃ + 0.342 𝐞₂₄ + 1.86 𝐞₂₅ + 0.0364 𝐞₃₄ + 0.829 𝐞₃₅ + 0.426 𝐞₄₅ + 9.54e-18 𝐞₁₂₃₄ + -5.55e-17 𝐞₁₂₃₅ + -4.16e-17 𝐞₂₃₄₅,
 2.02 + -0.873 𝐞₁₂ + -0.318 𝐞₁₃ + -0.152 𝐞₁₄ + 0.261 𝐞₁₅ + 0.507 𝐞₂₃ + 0.342 𝐞₂₄ + 1.86 𝐞₂₅ + 0.0364 𝐞₃₄ + 0.829 𝐞₃₅ + 0.426 𝐞₄₅ + 9.49e-18 𝐞₁₂₃₄ + -4.01e-18 𝐞₁₂₃₅ + -7e-18 𝐞₁₂₄₅ + 9.92e-18 𝐞₁₃₄₅ + -5.84e-18 𝐞₂₃₄₅,
 2.02 + 0.873 𝐞₁₂ + 0.318 𝐞₁₃ + 0.152 𝐞₁₄ + -0.261 𝐞₁₅ + -0.507 𝐞₂₃ + -0.342 𝐞₂₄ + -1.86 𝐞₂₅ + -0.0364 𝐞₃₄ + -0.829 𝐞₃₅ + -0.426 𝐞₄₅ + 9.49e-18 𝐞₁₂₃₄ + -4.01e-18 𝐞₁₂₃₅ + -7e-18 𝐞₁₂₄₅ + 9.92e-18 𝐞₁₃₄₅ + -5.84e-18 𝐞₂₃₄₅)

In [219]:
#8.16
S2 = S ** 2
blade = S2.grade(2)
bladesq = (blade ** 2)
bladesq

3.07 + 4.16e-17 𝐞₁₄ + 1.39e-16 𝐞₁₅ + 1.04e-16 𝐞₁₂₃₄ + 1.11e-16 𝐞₁₂₃₅ + 5.55e-17 𝐞₁₂₄₅ + -5.55e-17 𝐞₁₃₄₅ + -1.11e-16 𝐞₂₃₄₅

In [220]:
# 3 types of rotors (Spin+)
def type_convert(n):
    if n > 1e-6:
        return 1
    elif n < -1e-6:
        return -1
    else:
        return 0

# Unfortunately parabolic rotors are of measure zero, 
# so this function has zero chance generating them
def random_simple_rotor(alg, signature=None, max_iter=100):
    for _ in range(max_iter):
        S = random_versor(2, alg)
        if signature is not None:
            if type_convert((S.grade(2) ** 2)[0]) != signature:
                continue
        sign  = (S.reverse().sp(S))[0]
        if sign > 0:
            return normalize(S)
        
[random_simple_rotor(pseudo, signature=i) for i in range(-1, 2)]

[0.712 + -0.297 𝐞₁₂ + -0.414 𝐞₁₃ + -0.138 𝐞₁₄ + 0.0208 𝐞₁₅ + -0.632 𝐞₂₃ + -0.0365 𝐞₂₄ + 0.198 𝐞₂₅ + 0.243 𝐞₃₄ + 0.232 𝐞₃₅ + 0.0896 𝐞₄₅,
 None,
 1.9 + -0.159 𝐞₁₂ + 0.588 𝐞₁₃ + -0.696 𝐞₁₄ + -0.407 𝐞₁₅ + 0.825 𝐞₂₃ + -0.623 𝐞₂₄ + -0.322 𝐞₂₅ + -1.3 𝐞₃₄ + -0.921 𝐞₃₅ + 0.187 𝐞₄₅]

In [221]:
def simple_rotor_log(R: MultiVector, tol=1e-6):
    blade = R.grade(2)
    signature = (blade ** 2)[0]
    if signature > tol:
        return np.arccosh(R[0]) * normalize(blade)
    if signature < -tol:
        return np.arccos(R[0]) * normalize(blade)
    else:
        return blade

In [222]:
#8.17a elliptic rotor (rotation), run several times you can see sqrt allows a sign change
S = random_simple_rotor(pseudo, signature=-1)
S2 = S ** 2
b = simple_rotor_log(S2)
S2, blade_exp(b), blade_exp(b - 6*np.pi*b/norm(b)), S, blade_exp(b/2), simple_rotor_sqrt(S2), blade_exp(3.3*b).sw(S)

(0.256 + 0.596 𝐞₁₂ + -0.773 𝐞₁₃ + -0.261 𝐞₁₄ + 0.362 𝐞₁₅ + -0.758 𝐞₂₃ + -0.441 𝐞₂₄ + -0.000786 𝐞₂₅ + 0.239 𝐞₃₄ + 0.463 𝐞₃₅ + 0.269 𝐞₄₅ + -2.78e-17 𝐞₁₂₃₄ + 2.78e-17 𝐞₁₂₃₅ + 2.78e-17 𝐞₁₂₄₅ + 1.39e-17 𝐞₁₃₄₅,
 0.256 + 0.596 𝐞₁₂ + -0.773 𝐞₁₃ + -0.261 𝐞₁₄ + 0.362 𝐞₁₅ + -0.758 𝐞₂₃ + -0.441 𝐞₂₄ + -0.000786 𝐞₂₅ + 0.239 𝐞₃₄ + 0.463 𝐞₃₅ + 0.269 𝐞₄₅,
 0.256 + 0.596 𝐞₁₂ + -0.773 𝐞₁₃ + -0.261 𝐞₁₄ + 0.362 𝐞₁₅ + -0.758 𝐞₂₃ + -0.441 𝐞₂₄ + -0.000786 𝐞₂₅ + 0.239 𝐞₃₄ + 0.463 𝐞₃₅ + 0.269 𝐞₄₅,
 0.793 + 0.376 𝐞₁₂ + -0.488 𝐞₁₃ + -0.165 𝐞₁₄ + 0.229 𝐞₁₅ + -0.478 𝐞₂₃ + -0.278 𝐞₂₄ + -0.000496 𝐞₂₅ + 0.151 𝐞₃₄ + 0.292 𝐞₃₅ + 0.169 𝐞₄₅,
 0.793 + 0.376 𝐞₁₂ + -0.488 𝐞₁₃ + -0.165 𝐞₁₄ + 0.229 𝐞₁₅ + -0.478 𝐞₂₃ + -0.278 𝐞₂₄ + -0.000496 𝐞₂₅ + 0.151 𝐞₃₄ + 0.292 𝐞₃₅ + 0.169 𝐞₄₅,
 0.793 + 0.376 𝐞₁₂ + -0.488 𝐞₁₃ + -0.165 𝐞₁₄ + 0.229 𝐞₁₅ + -0.478 𝐞₂₃ + -0.278 𝐞₂₄ + -0.000496 𝐞₂₅ + 0.151 𝐞₃₄ + 0.292 𝐞₃₅ + 0.169 𝐞₄₅ + -1.75e-17 𝐞₁₂₃₄ + 1.75e-17 𝐞₁₂₃₅ + 1.75e-17 𝐞₁₂₄₅ + 8.75e-18 𝐞₁₃₄₅,
 0.793 + 0.376 𝐞₁₂ + -0.488 𝐞₁₃ + -0.165 𝐞₁₄ +

In [223]:
#8.17b hyperbolic rotor (boost)
S = random_simple_rotor(pseudo, signature=1)
S2 = S ** 2
b = simple_rotor_log(S2)
S2, blade_exp(b), S, blade_exp(b/2), simple_rotor_sqrt(S2), blade_exp(3.3*b).sw(S)

(1.68 + -0.483 𝐞₁₂ + -0.49 𝐞₁₃ + -1.23 𝐞₁₄ + -0.983 𝐞₁₅ + -0.155 𝐞₂₃ + -0.371 𝐞₂₄ + -0.0599 𝐞₂₅ + 0.0177 𝐞₃₄ + 0.254 𝐞₃₅ + 0.602 𝐞₄₅ + 2.86e-17 𝐞₁₂₃₄ + -3.47e-18 𝐞₁₂₃₅ + -5.55e-17 𝐞₁₂₄₅ + -1.73e-17 𝐞₂₃₄₅,
 1.68 + -0.483 𝐞₁₂ + -0.49 𝐞₁₃ + -1.23 𝐞₁₄ + -0.983 𝐞₁₅ + -0.155 𝐞₂₃ + -0.371 𝐞₂₄ + -0.0599 𝐞₂₅ + 0.0177 𝐞₃₄ + 0.254 𝐞₃₅ + 0.602 𝐞₄₅,
 -1.16 + 0.209 𝐞₁₂ + 0.212 𝐞₁₃ + 0.531 𝐞₁₄ + 0.425 𝐞₁₅ + 0.067 𝐞₂₃ + 0.16 𝐞₂₄ + 0.0259 𝐞₂₅ + -0.00763 𝐞₃₄ + -0.11 𝐞₃₅ + -0.26 𝐞₄₅,
 1.16 + -0.209 𝐞₁₂ + -0.212 𝐞₁₃ + -0.531 𝐞₁₄ + -0.425 𝐞₁₅ + -0.067 𝐞₂₃ + -0.16 𝐞₂₄ + -0.0259 𝐞₂₅ + 0.00763 𝐞₃₄ + 0.11 𝐞₃₅ + 0.26 𝐞₄₅,
 1.16 + -0.209 𝐞₁₂ + -0.212 𝐞₁₃ + -0.531 𝐞₁₄ + -0.425 𝐞₁₅ + -0.067 𝐞₂₃ + -0.16 𝐞₂₄ + -0.0259 𝐞₂₅ + 0.00763 𝐞₃₄ + 0.11 𝐞₃₅ + 0.26 𝐞₄₅ + 1.24e-17 𝐞₁₂₃₄ + -1.5e-18 𝐞₁₂₃₅ + -2.4e-17 𝐞₁₂₄₅ + -7.49e-18 𝐞₂₃₄₅,
 -1.16 + 0.209 𝐞₁₂ + 0.212 𝐞₁₃ + 0.531 𝐞₁₄ + 0.425 𝐞₁₅ + 0.067 𝐞₂₃ + 0.16 𝐞₂₄ + 0.0259 𝐞₂₅ + -0.00763 𝐞₃₄ + -0.11 𝐞₃₅ + -0.26 𝐞₄₅ + 4.26e-14 𝐞₁₂₃₄ + -1.42e-14 𝐞₁₂₃₅ + -1.14e-13 𝐞₁₂₄₅ + -5.33e-1

In [224]:
#8.17c 8.20 parabolic rotor (translation)
S = (e2 + e3 - e4) * e2
S2 = S ** 2
b = simple_rotor_log(S2)
S2, blade_exp(b), S, blade_exp(b/2), simple_rotor_sqrt(S2), blade_exp(3.3*b).sw(S)

(1 + -2 𝐞₂₃ + 2 𝐞₂₄,
 1 + -2 𝐞₂₃ + 2 𝐞₂₄,
 1 + -1 𝐞₂₃ + 1 𝐞₂₄,
 1 + -1.0 𝐞₂₃ + 1.0 𝐞₂₄,
 1.0 + -1.0 𝐞₂₃ + 1.0 𝐞₂₄,
 1.0 + -1.0 𝐞₂₃ + 1.0 𝐞₂₄)

In [225]:
#8.21
B = S.grade(2) / (1 + S.grade(0))
B, (1+B)**2/(normsq(1+B)), S

(-0.5 𝐞₂₃ + 0.5 𝐞₂₄, 1.0 + -1.0 𝐞₂₃ + 1.0 𝐞₂₄, 1 + -1 𝐞₂₃ + 1 𝐞₂₄)

In [274]:
#8.25
R, u = random_rotor(pseudo), random_r_blade(1, pseudo)
v = R.sw(u)
S = simple_rotor_sqrt(v * u / normsq(u))
U = S.reverse() * R
R, S * U, S * u, u * S.reverse(), U * u, u * U

(1.61 + -1.12 𝐞₁₂ + -0.623 𝐞₁₃ + -1.89 𝐞₁₄ + -1.51 𝐞₁₅ + 0.724 𝐞₂₃ + -0.624 𝐞₂₄ + 1.15 𝐞₂₅ + -1.13 𝐞₃₄ + 0.17 𝐞₃₅ + 2.23 𝐞₄₅ + -0.308 𝐞₁₂₃₄ + -0.352 𝐞₁₂₃₅ + 0.392 𝐞₁₂₄₅ + 0.398 𝐞₁₃₄₅ + 0.261 𝐞₂₃₄₅,
 1.61 + -1.12 𝐞₁₂ + -0.623 𝐞₁₃ + -1.89 𝐞₁₄ + -1.51 𝐞₁₅ + 0.724 𝐞₂₃ + -0.624 𝐞₂₄ + 1.15 𝐞₂₅ + -1.13 𝐞₃₄ + 0.17 𝐞₃₅ + 2.23 𝐞₄₅ + -0.308 𝐞₁₂₃₄ + -0.352 𝐞₁₂₃₅ + 0.392 𝐞₁₂₄₅ + 0.398 𝐞₁₃₄₅ + 0.261 𝐞₂₃₄₅,
 1.85 𝐞₁ + 0.477 𝐞₂ + 0.84 𝐞₃ + 0.257 𝐞₄ + 1.97 𝐞₅ + -5.55e-17 𝐞₁₂₃ + -5.55e-17 𝐞₁₂₅ + -3.08e-33 𝐞₁₃₄ + -2.22e-16 𝐞₁₃₅ + -6.94e-18 𝐞₁₄₅ + 6.94e-18 𝐞₂₃₄ + 1.54e-33 𝐞₂₃₅ + 6.94e-18 𝐞₂₄₅ + 4.16e-17 𝐞₃₄₅ + -7.46e-17 𝐞₁₂₃₄₅,
 1.85 𝐞₁ + 0.477 𝐞₂ + 0.84 𝐞₃ + 0.257 𝐞₄ + 1.97 𝐞₅ + 5.55e-17 𝐞₁₂₃ + -1.07e-18 𝐞₁₂₄ + 5.55e-17 𝐞₁₂₅ + 3.76e-18 𝐞₁₃₄ + 2.22e-16 𝐞₁₃₅ + 6.07e-18 𝐞₁₄₅ + -1.63e-18 𝐞₂₃₄ + 4.16e-17 𝐞₂₃₅ + -6.94e-18 𝐞₂₄₅ + -4.16e-17 𝐞₃₄₅ + -7.46e-17 𝐞₁₂₃₄₅,
 0.558 𝐞₁ + 0.211 𝐞₂ + 0.593 𝐞₃ + 0.0758 𝐞₄ + 0.503 𝐞₅ + -0.0796 𝐞₁₂₃ + -0.0215 𝐞₁₂₄ + 0.248 𝐞₁₂₅ + 0.276 𝐞₁₃₄ + 0.421 𝐞₁₃₅ + 0.254 𝐞₁₄₅ + 0.116 𝐞₂₃₄

In [276]:
def gprod(vectors) -> MultiVector:
    return reduce(lambda a, b: a * b, vectors, 1)

def rotor_split(R: MultiVector, alg: Algebra, tol=1e-6):
    # FIXME: when the tangent not well defined
    assert normsq(R.grade(2)) > tol, "zero bivector"
    tangent = R.grade(2) / R[0]
    tangents = bivector_split(tangent, alg)
    splits = sorted([normalize(1 + t) for t in tangents], key=lambda item: abs(item[0]))
    sign = np.round(gprod(r[0] for r in splits)/R[0])
    splits[0] = splits[0] * sign # to keep the sign of R
    return splits
        

R_splits = rotor_split(R, pseudo)
R, gprod(R_splits), gprod([blade_exp(simple_rotor_log(r)) for r in R_splits])

(1.61 + -1.12 𝐞₁₂ + -0.623 𝐞₁₃ + -1.89 𝐞₁₄ + -1.51 𝐞₁₅ + 0.724 𝐞₂₃ + -0.624 𝐞₂₄ + 1.15 𝐞₂₅ + -1.13 𝐞₃₄ + 0.17 𝐞₃₅ + 2.23 𝐞₄₅ + -0.308 𝐞₁₂₃₄ + -0.352 𝐞₁₂₃₅ + 0.392 𝐞₁₂₄₅ + 0.398 𝐞₁₃₄₅ + 0.261 𝐞₂₃₄₅,
 1.61 + -1.12 𝐞₁₂ + -0.623 𝐞₁₃ + -1.89 𝐞₁₄ + -1.51 𝐞₁₅ + 0.724 𝐞₂₃ + -0.624 𝐞₂₄ + 1.15 𝐞₂₅ + -1.13 𝐞₃₄ + 0.17 𝐞₃₅ + 2.23 𝐞₄₅ + -0.308 𝐞₁₂₃₄ + -0.352 𝐞₁₂₃₅ + 0.392 𝐞₁₂₄₅ + 0.398 𝐞₁₃₄₅ + 0.261 𝐞₂₃₄₅,
 1.61 + -1.12 𝐞₁₂ + -0.623 𝐞₁₃ + -1.89 𝐞₁₄ + -1.51 𝐞₁₅ + 0.724 𝐞₂₃ + -0.624 𝐞₂₄ + 1.15 𝐞₂₅ + -1.13 𝐞₃₄ + 0.17 𝐞₃₅ + 2.23 𝐞₄₅ + -0.308 𝐞₁₂₃₄ + -0.352 𝐞₁₂₃₅ + 0.392 𝐞₁₂₄₅ + 0.398 𝐞₁₃₄₅ + 0.261 𝐞₂₃₄₅)

In [277]:
#8.10 a spinor is an even versor for odd dimension (a Dirac representation);
# a sum of an even versor and its dual for even dimension (two Weyl representations)
def random_study_number(alg):
    a, b = np.random.rand(2)
    return (a + alg.pseudoscalar((b,)))

def random_spinor(alg: Algebra):
    if alg.d % 4:
        return random_even_versor(alg)
    return random_study_number(alg) * random_even_versor(alg)

random_spinor(Algebra(3)), random_spinor(Algebra(4))


(0.732 + 0.0932 𝐞₁₂ + 0.0372 𝐞₁₃ + -0.0678 𝐞₂₃,
 0.0905 + -0.502 𝐞₁₂ + 0.118 𝐞₁₃ + -0.0126 𝐞₁₄ + 0.0833 𝐞₂₃ + 0.0975 𝐞₂₄ + 0.34 𝐞₃₄ + -0.0176 𝐞₁₂₃₄)

In [60]:
# A pointor depends on a point
def random_point(alg: Algebra):
    return random_r_blade(alg.d - 1, alg)

O = random_point(alg)

# point reflection on the point itself is a pointor
terms_ratio(O, O.sw(O))

array([-33.57429333, -33.57429333, -33.57429333, -33.57429333])

In [61]:
# versors not crossing O-subspace are pointers 
vectors = blade_split(O, alg)
B1, B2 = wedge(vectors[:2]), wedge(vectors[1:])
Od = O.dual()
terms_ratio(O, Od.sw(O)), terms_ratio(B1.sw(O), O), terms_ratio(vectors[0].sw(O), O), 

(array([-33.57429333, -33.57429333, -33.57429333, -33.57429333]),
 array([12.90591293, 12.90591293, 12.90591293, 12.90591293]),
 array([13.36279296, 13.36279296, 13.36279296, 13.36279296]))

In [62]:
# rotors with reflections are pointers
R1 = blade_exp(3.3*B1)
R2 = blade_exp(4.4*B2)
terms_ratio((Od * R1 * R2).sw(O), O), terms_ratio((Od * vectors[2] * R1).sw(O), O)

(array([-0.02978469, -0.02978469, -0.02978469, -0.02978469]),
 array([0.03264996, 0.03264996, 0.03264996, 0.03264996]))

In [63]:
# rotors cross O-subspace may not be pointers
terms_ratio(blade_exp(Od ^ vectors[2]).sw(O), O)

array([2.31265738, 1.17541562, 1.17541562, 1.17541562])

In [64]:
# A general pointor suggested by "From Invariant Decomposition to Spinors"?
# How do we find the point specified by a pointor?
def random_odd_versor(alg):
    d = alg.d
    if not (alg.d % 2):
        d -= 1
    return gprod(random_r_vectors(d, alg))


# Actually I'm not sure these generate pointors
# def random_pointor(alg: Algebra):
#     return random_odd_versor(alg) * random_even_versor(alg)
    
# def random_pointor(alg: Algebra):
#     v = random_r_blade(1, alg)
#     return (np.random.rand() + v) * random_even_versor(alg)

# FIXME: check degree of freedom
def random_pointor(alg: Algebra):
    v = random_r_blade(1, alg)
    return (np.random.rand() + v) * random_versor(2, alg)

pointor = random_pointor(alg)
pointor

0.485 + 0.228 𝐞₁ + 0.447 𝐞₂ + 0.646 𝐞₃ + 0.0591 𝐞₄ + -0.0795 𝐞₁₂ + -0.0623 𝐞₁₃ + -0.0573 𝐞₁₄ + 0.116 𝐞₂₃ + -0.032 𝐞₂₄ + -0.108 𝐞₃₄ + 0.00599 𝐞₁₂₃ + 0.0281 𝐞₁₂₄ + 0.0177 𝐞₁₃₄ + -0.0433 𝐞₂₃₄

In [65]:
# the point-grade
O = pointor.grade(3)
terms_ratio(pointor.sw(O), O)

array([0.90449692, 0.90449692, 0.90449692, 0.90449692])